name: costmate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  cloud_firestore: ^5.6.5
  intl: ^0.20.2
  image_picker: ^1.1.2
  image_picker_web: ^2.0.0
  timeago: ^3.0.2
  http: ^1.4.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  flutter_riverpod: ^2.6.1
  rxdart: ^0.28.0
  another_flushbar: ^1.12.30
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/costmateLogo.png"